#3 Support config file
allwefantasy/mlsql-deploy pull request #5
Opened 2021-09-17 09:20 UTC by chncaesar

## What changes are proposed?
To support arbitrary configurations from a file, add a new flag --conf-file, this flag is optional.

### Usage
Create a configuration file. Please note: 
 - Each config is in key=value format.
 - Each config should start with engine, otherwise it'd be silently ignored.
 - engine.spark.* config goes to spark-submit 
 - engine.storage.* config goes to core-site.xml

example:  ~/.engine.config. 
```shell
engine.spark.kubernetes.container.image.pullPolicy=Always
engine.storage.key=value
```

Running mlsql-deploy command 
```shell
./mlsql-deploy run \
--kube-config ~/.kube/config \
--engine-name mlsql-k8s --engine-image techmlsql/mlsql-engine:3.0-2.1.0 \
--engine-executor-core-num 2 \
--engine-executor-num 1 \
--engine-executor-memory 2048 \
--engine-driver-core-num 2 \
--engine-driver-memory 2048 \
--engine-access-token mlsql \
--engine-jar-path-in-container local:///home/deploy/mlsql/libs/streamingpro-mlsql-spark_3.0_2.12-2.1.0.jar \
--storage-name jfs \
--storage-meta-url redis://127.0.0.1:6379/1 \
--conf-file ~/.engine.config
```

## How was this PR tested?
-[x] unit-test main_test.go and utils_test.go are passed
-[x] manually tested

2021-09-17 10:17 UTC, allwefantasy requested changes

2021-09-18 06:16 UTC, chncaesar commented on cmd/run.go
> +	var sparkConf, arbitraryStorageConfig map[string]string
Changed.

2021-09-18 06:18 UTC, chncaesar commented on cmd/run.go
> +	var confErr error
changed

2021-09-18 06:18 UTC, chncaesar commented on cmd/run.go
> +			ArbitraryConfig: &arbitraryStorageConfig,
changed

2021-09-18 06:18 UTC, chncaesar commented on pkg/utils/utils.go
> +func ReadConfigFile(path string) (map[string]string, map[string]string, error) {
The new function
```go
convertToConfString := func(extraConfMap map[string]string,
		converter func(key, value string) string) string
```

2021-09-18 06:19 UTC, chncaesar commented on pkg/tpl/templates/deployment.yaml
> +            {{ range $key, $value := .EngineConfig.SparkConfig -}}
Changed

2021-09-18 09:42 UTC, allwefantasy approved these changes

2021-09-18 09:42 UTC, merged